In [131]:
import time

import numpy as np
import pandas as pd

In [161]:
with open('input.txt') as f:
    lines = f.read().strip()
lines = lines.replace('A', '1').replace('B', '2').replace('C', '3')
lines = lines.split('\n')

In [158]:
def get_outcome(line, is_part1=True):
    line = line.replace('X', '1').replace('Y', '2').replace('Z', '3')

    shape1, shape2 = line.split(' ')
    shape1 = int(shape1) # opponent
    shape2 = int(shape2) # me

    # point_shape
    point_shape = shape2

    # point_win
    # rock1, paper2, scissors3
    result = shape1-shape2
    if result == 0:
        point_win = 3
    elif (result == 1) or (result == -2):
        point_win = 0
    elif (result == -1) or (result == 2):
        point_win = 6

    return point_shape, point_win

In [162]:
time_start = time.time()
scores = []
for line in lines:
    point_shape, point_win = get_outcome(line)
    scores.append(point_shape + point_win)
np.sum(scores)
print(f'elapsed time: {time.time() - time_start:.5}[s]')

elapsed time: 0.0051134[s]

In [35]:
def get_outcome2(line):
    shape1, shape2_ = line.split(' ')
    shape1 = int(shape1) # opponent
    #shape2 = int(shape2) # me

    # point_shape
    #point_shape = shape2

    if shape1 == 1:
        if shape2_ == 'X':
            shape2 = 3
        elif shape2_ == 'Y':
            shape2 = 1
        elif shape2_ == 'Z':
            shape2 = 2
    elif shape1 == 2:
        if shape2_ == 'X':
            shape2 = 1
        elif shape2_ == 'Y':
            shape2 = 2
        elif shape2_ == 'Z':
            shape2 = 3
    elif shape1 == 3:
        if shape2_ == 'X':
            shape2 = 2
        elif shape2_ == 'Y':
            shape2 = 3
        elif shape2_ == 'Z':
            shape2 = 1

    point_shape = shape2
    if shape2_ == 'X':
        point_win = 0
    elif shape2_ == 'Y':
        point_win = 3
    elif shape2_ == 'Z':
        point_win = 6

    return point_shape, point_win

In [36]:
scores = []
lines_ = lines.replace('A', '1').replace('B', '2').replace('C', '3')
lines_ = lines_.split('\n')
for line in lines_:
    point_shape, point_win = get_outcome2(line)
    scores.append(point_shape + point_win)
np.sum(scores)

13490

## using look-up table.

In [176]:
## make look-up table.
lookup_list = [
    ["rock", "rock", 3],
    ["rock", "paper", 0],
    ["rock", "scissors", 6],
    ["scissors", "rock", 0],
    ["scissors", "paper", 6],
    ["scissors", "scissors", 3],
    ["paper", "rock", 6],
    ["paper", "paper", 3],
    ["paper", "scissors", 0]
              ]
column_names = ["shape_me", "shape_opponent", "point_win"]
df = pd.DataFrame(data=lookup_list, columns=column_names)

# add point of the shape
df['point_shape'] = df['shape_me'].replace('rock', 1).replace('paper', 2).replace('scissors', 3)
# total = shape + win/lose/draw
df['point_total'] = df['point_win'] + df['point_shape']

df

   shape_me shape_opponent  point_win  point_shape  point_total
0      rock           rock          3            1            4
1      rock          paper          0            1            1
2      rock       scissors          6            1            7
3  scissors           rock          0            3            3
4  scissors          paper          6            3            9
5  scissors       scissors          3            3            6
6     paper           rock          6            2            8
7     paper          paper          3            2            5
8     paper       scissors          0            2            2

In [ ]:
## load data.
with open('input.txt') as f:
    lines = f.read().strip().split('\n')

dic_opponent = {'A':'rock', 'B':'paper', 'C':'scissors'}
dic1 = {'X':'rock', 'Y':'paper', 'Z':'scissors'}
dic2 = {'X':0, 'Y':3, 'Z':6}

In [133]:
time_start = time.time()
is_part1 = True
scores = 0
for line in lines:
    x = [dic_opponent.get(i, i) for i in list(line)]
    x.remove(' ')
    
    if is_part1:
        x = [dic1.get(i, i) for i in list(x)]
        idx = np.where((df['shape_opponent']==x[0]) & (df['shape_me']==x[1]))
    else:
        x = [dic2.get(i, i) for i in list(x)]
        idx = np.where((df['shape_opponent']==x[0]) & (df['point_win']==x[1]))
    
    scores += df._get_value(idx[0][0], 'point_total')
print(f'total score:{scores}')
print(f'elapsed time: {time.time() - time_start:.2}[s]')

total score:17189
elapsed time: 0.64231[s]

In [177]:
df['col1'] = df['shape_opponent'].replace('rock', 'A').replace('paper', 'B').replace('scissors', 'C')
df['col2_1'] = df['shape_me'].replace('rock', 'X').replace('paper', 'Y').replace('scissors', 'Z')
df['col2_2'] = df['point_win'].replace(0, 'X').replace(3, 'Y').replace(6, 'Z')

df.sort_values(by=['point_total'])

,shape_me,shape_opponent,point_win,point_shape,point_total,col1,col2_1,col2_2
1,rock,paper,0,1,1,B,X,X
8,paper,scissors,0,2,2,C,Y,X
3,scissors,rock,0,3,3,A,Z,X
0,rock,rock,3,1,4,A,X,Y
7,paper,paper,3,2,5,B,Y,Y
5,scissors,scissors,3,3,6,C,Z,Y
2,rock,scissors,6,1,7,C,X,Z
6,paper,rock,6,2,8,A,Y,Z
4,scissors,paper,6,3,9,B,Z,Z

In [174]:
with open('input.txt') as f:
    lines = f.read().strip().split('\n')
map1 = ['', 'B X', 'C Y', 'A Z', 'A X', 'B Y', 'C Z', 'C X', 'A Y', 'B Z']
map2 = ['', 'B X', 'C X', 'A X', 'A Y', 'B Y', 'C Y', 'C Z', 'A Z', 'B Z']

time_start = time.time()
scores = 0
for line in lines:
    ## part 1
    #scores += map1.index(line)
    ## part 2
    scores += map2.index(line)
print(f'total score:{scores}')
print(f'elapsed time: {time.time() - time_start:.5}[s]')

total score:13490
elapsed time: 0.00070477[s]

In [154]:
data = 'A Z'

## using dict.
dic_ = {'A':1, 'B':2, 'C':3, 'X':1, 'Y':2, 'Z':3}
time_start = time.time()
data_ = [dic_.get(d, d) for d in data]
data_.remove(' ')
print(f'elapsed time: {time.time() - time_start:.5}[s]')

## using replace.
time_start = time.time()
data_ = data.replace('A', '1').replace('B', '2').replace('C', '3').replace('X', '1').replace('Y', '2').replace('Z', '3')
print(f'elapsed time: {time.time() - time_start:.5}[s]')

elapsed time: 7.7486e-05[s]
elapsed time: 7.2956e-05[s]